### ISSUE TITLE
x64 Support isn't working

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/snek#1]

**Comment by den-run-ai** [comment]
very cool project, i first tried powershell+pythonnet few years ago. what error do you get on x64?

https://stackoverflow.com/a/39543595/2230844

**Comment by adamdriscoll** [comment]
Honestly, just had a user email me about it and threw this issue in so I could test it out later and forgot. But I have no problem running x64 on my machine. 

```
PS C:\Users\Adam> import-module snek
PS C:\Users\Adam> Use-Python {
>>     Invoke-Python -Code "print('hi!')"
>> }
hi!
PS C:\Users\Adam>     [IntPtr]::Size
8
```
