### ISSUE TITLE
can it be made to work cross platform on linux and macosx?

### ISSUE THREAD

**Issue by TheBigBear** [adamdriscoll/snek#6]
This installs fine on linux and macosx but the provided DLLs are ( presumably ? ) windows only and won't actually work on linux or macosx?

Is there some intelligence you can add to your snek.psm1 file to cause powershell to indicate it is windows ONLY and won't work under linux or macosx? 

Or what would it take to add the linux and macosx shared libraries so it works across platforms? (i.e. is there anything I can do to help and add the relevant shared library binary files to this repo? )

**Comment by adamdriscoll** [comment]
This has been added and snek 2.0 has beenpublished.
