### ISSUE TITLE
can python 3.8 and 3.9 be added? 

### ISSUE THREAD

**Issue by TheBigBear** [adamdriscoll/snek#7]
Hi Adam,

How and where do you go to extract the windows dll from? could you put a note in the top level readme, please? Armed with that info I will then have a go at finding and extracting the equivalent linux and Mac OS dynamic libraries and see if they can be similarly added to make this actually cross-platform.

**Comment by adamdriscoll** [comment]
This has been added and Snek 2.0 has been published.
